# Aula06 - Pandas I

# Agenda

O objetivo dessa aula é introduzir a biblioteca Pandas:
+ Series
+ DataFrames

# Pandas (Parte I)

# Series

**Tópicos**:
* Pandas Series:

 - Series vs Numpy Arrays
 - Inicialização de Series
 - Operações Básicas com Series
 - Concatenação de Series

A Series é o objeto base do Pandas, assim como o array é o do numpy.

* Três estruturas importantes:
    + `Series`
    + `DataFrame`
    + `Index`

In [ ]:
import numpy as np
import pandas as pd

## Series vs Numpy

* Visualização
* Índice

In [ ]:
# Visualização
# Numpy

In [ ]:
# Visualização
#Pandas

+ Array do Numpy retorna um formato horizontal (1D)
+ Series do Pandas retorna um formato vertical (Coluna).



```
# Isto está formatado como código
```

* **Índice (Index)**

+ No Numpy os arrays possuem índices numéricos (0, 1, 2, 3). 
+ No Pandas os índices podem ser numéricos e também strings.

In [ ]:
series_exemplo = pd.Series([1,2,3,4], index=['numero_1', 'numero_2', 'numero_3', 'numero_4'])
series_exemplo

Podemos acessar o dado como fazíamos nas listas e arrays, por meio do índice.

In [ ]:
#mesmo tendo alterado a descrição do índice para strings, é possível referenciá-lo na forma numérica

In [ ]:
#quando selecionamos um intervalo pelo indice numerico, o padrao do Python é considerar ">= e <" que os indices declarados.
#mas quando referenciamos pelo indice transformado em string, é considerado ">= e <=".

Podemos acessar os valores

Podemos acessar seus índices

## Criação de Series

* Podemos construir `Series` partindo do zero. A forma geral de fazer isso é a seguinte:

```python
pd.Series(data, index = index)
```
* `index` é um argumento opcional e `data` pode ser várias coisas

In [ ]:
# Series com um único valor

In [ ]:
# Dicionário

## Operações Básicas Com Series

In [ ]:
series1 = pd.Series([1,2,3], index=['carne', 'carneiro', 'ovelha'])
series2 = pd.Series([2,3,4], index=['ovo', 'carneiro', 'ovelha'])

In [ ]:
# Soma

In [ ]:
# Divisão

In [ ]:
# Subtração

In [ ]:
# Multiplicação

NaN
+ como o indice "carne" nao existe em "series2", e "ovo" não existe em "series1", nas operações acima, uma das parcelas ou fatores entra como um elemento nulo (NaN), e operações com NaN não são possiveis, resultando em também em NaN.

## Filtros
o Filtro é como se estivéssemos comparando elemento por elemento e fazendo a comparação desejada.

In [ ]:
# filtros

In [ ]:
# se quisermos conhecer os valores

In [ ]:
# Se quisermos a negação da condição

## Outras possibilidades com Series

In [ ]:
series1.sum()

In [ ]:
series1.std()

In [ ]:
series1.max()

In [ ]:
series1.min()

In [ ]:
series1.count()

In [ ]:
series1.unique()

In [ ]:
series1.nunique()

In [ ]:
series1.value_counts()

E se quisermos criar um novo elemento com um novo índice?

Podemos checar se o valor de uma series existe em outra series ou lista.

In [ ]:
print(series1)
print('')
print(series2)

In [ ]:
#isin

In [ ]:
#Como mostrar quais são os valores em comum?

In [ ]:
#Como mostrar quais são os índices em comum?

## Concatenação de Series

In [ ]:
print(series1)
print('')
print(series2)

In [ ]:
#No Numpy não era possivel concatenar array com dimensoes diferentes, 
#já com Series do Pandas é possivel devido a utilização dos indices

## Exercícios

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5, 6])
ser2 = pd.Series([4, 5, 6, 7, 8, 9])

1. Retornar os valores de ser1 que não estão em ser2

2. Retornar os valores comuns a ser1 e ser2 que sejam pares

# DataFrames

**Tópicos**:
* Pandas DataFrames:
 - O que é um DataFrame ?
 - Inicialização de um dataframe
 - Carregando dados de um csv e do excel com Pandas
 - Atributos de um DataFrame
 - Acessando dados 
 - Ordenação e Descrição 
 - Transformando os dados
 - Filtrando Dados
 - Mudança Condicional
 - Exercícios
 - Exportando o Data Frame

## O que é um DataFrame ?

O Pandas DataFrame é uma estrutura de dados tabular bidimensional de tamanho variável, podendo ou não ser heterogênea (vários tipos de dados), com eixos rotulados (linhas e colunas). O arranjo de um DataFrame permite a distribuição dos dados em linhas e colunas. Assim, podemos destacar três componentes presentes em um data frame: 
+ linhas
+ colunas
+ valores

<img src=https://media.geeksforgeeks.org/wp-content/uploads/finallpandas.png width=700 height=500>

## Criação de um Data Frame

Para inicializar um data fame utilizamos a função abaixo:

pandas.DataFrame(```data```, ```index```, ```columns```, ```dtype```)

* ```data```: numpy array, listas, series
* ```index```:  É opcional. Caso não seja informado, um objeto np.arange(m) será utilizado
* ```columns```: Também é opcional e é inicializado como np.arange(n) se não passado.
* ```dtype```: tipo de dado das colunas

In [ ]:
# Inicializando um dataframe vazio

Podemos iniciar um data frame a partir de diversas outras estrutura, tais como:
* Listas
* Dicionários
* Arrays
* Series

* Data Frame a partir de uma lista

* Data Frame a partir de um dicionário

* Array Numpy

In [ ]:
arr = np.arange(10)
df_array = pd.DataFrame(data=arr)
print(f'{arr}\n')
df_array

* Series

In [ ]:
series = pd.Series([1,2,3,4])
df_series = pd.DataFrame(series)
print(f'{series}\n')
df_series

## Carregando dados de um csv e do excel com Pandas

No dia a dia é mais comum que tenhamos acesso à fontes de dados em arquivos de formato csv, xlsx, ou acesso direto a bancos de dados. Dessa forma, o pandas pode ser utilizado parar carregar os dados disponíveis em formato de data frame.

Aqui iremos demonstrar o carregamento de um arquivo csv.

Mas o que é um arquivo csv?

CSV: **C**omma **S**eparated **V**alues<br>
Arquivo separado por vírgulas.

<img src=https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/1080247870/original/UDHlNQUo4ju-0SSFws_XskGYvIf5KZNn4w.png?1563457877>

Trazendo dados de um csv

pd.```read_csv```<br>
<a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html">Clique Aqui</a> para saber mais!

pd.read_csv(```file_path_buffer```, ```delimiter```)

* ```filepath_or_buffer```: Caminho do arquivo. Pode ser também um link da internet (github, kaggle)
* ```delimiter```: Pode ser ','   ';'    entre outros.

In [ ]:
# A partir de uma URL (Jupyter ou Colab)
url= "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
df_countries = pd.read_csv(filepath_or_buffer=url)
df_countries

In [ ]:
# No Jupyter: partir de um arquivo local
# No Colab: fazendo previamente o upload do arquivo na sessão
df_pokemons = pd.read_csv('pokemon_data.csv', index_col=0)
df_pokemons

In [ ]:
#Somente no Colab
from google.colab import files
uploaded = files.upload()

import io
df_pokemons = pd.read_csv(io.BytesIO(uploaded['pokemon_data.csv']), index_col=0)
# Agora o Dataset está armazenado no Pandas Dataframe
df_pokemons

A partir de um xlsx também podemos obter dados. O xlsx é uma extensão do excel.

In [ ]:
# No Jupyter: partir de um arquivo local
# No Colab: fazendo previamente o upload do arquivo na sessão
df_pokemons_excel = pd.read_excel('pokemon_data.xlsx')

In [ ]:
df_pokemons_excel

In [ ]:
#Somente no Colab

from google.colab import files
uploaded = files.upload()

import io
df_pokemons_excel = pd.read_excel(io.BytesIO(uploaded['pokemon_data.xlsx']), index_col=0)
# Agora o Dataset está armazenado no Pandas Dataframe
df_pokemons_excel

## Atributos de um Data Frame

In [ ]:
# Colunas

In [ ]:
# Índice

In [ ]:
# Shape

In [ ]:
# valores (dados)

In [ ]:
#Verificando os tipos de cada coluna

## Acessando dados

In [ ]:
#Head: primeiras 5 linhas (também é possível definir o número de linhas a serem visualizadas)
#df_countries.head()

In [ ]:
#Tail: últimas 5 linhas (também é possível definir o número de linhas a serem visualizadas)

In [ ]:
#Sample: retorna uma linha aleatória (também é possível definir o número de linhas a serem visualizadas)

In [ ]:
#Shape: Linhas, Colunas

In [ ]:
# Acessando colunas - Método 1

In [ ]:
# Acessando colunas - Método 2 (desde que não haja espaço no nome da coluna)

Podemos acessar linhas e colunas simultaneamente por meio dos comandos ```.iloc``` e ```.loc```

In [ ]:
# .iloc: acessando linhas e colunas pelos índices

In [ ]:
# .loc: acessando linhas e colunas pelos valores
df_pokemons.loc[df_pokemons['Name']=='Bulbasaur',['Name','HP']]

## Ordenação e Descrição

In [ ]:
# Ordenando por HP (ordem crescente ou decrescente)

In [ ]:
# Ordenando por mais de uma coluna (ambas em ordem crescente)

In [ ]:
# Ordenando por mais de uma coluna (primeira crescente, segunda decrescente)
df_pokemons.sort_values(['HP', 'Attack'], ascending=[True,False]).head()

In [ ]:
# Descrevendo dados numéricos

In [ ]:
# Descrevendo dados categóricos

## Transformando os dados

In [ ]:
df_pokemons[['Attack','Sp. Atk']].head()

In [ ]:
# Combinando os attacks e criando uma nova coluna
df_pokemons['Total_Attack'] = df_pokemons['Attack'] + df_pokemons['Sp. Atk']
df_pokemons[['Attack','Sp. Atk','Total_Attack']].head()

In [ ]:
# Excluindo uma coluna
df_pokemons.drop('Total_Attack', axis=1, inplace=True) # inplace=True para substituir no data frame original
#df_pokemons = df_pokemons.drop('Total_Attack', axis=1)
df_pokemons.columns

## Filtrando Dados

Podemos filtrar as linhas do data frame baseando-se em condições.

In [ ]:
#Uma condição

In [ ]:
#.loc

In [ ]:
# condições múltiplas ('&' equivale a 'and',  '|' equivale a 'or')
df_pokemons[(df_pokemons.HP>100) & (df_pokemons.Attack<80)].head()

In [ ]:
#.loc ('&' equivale a 'and',  '|' equivale a 'or')
df_pokemons.loc[(df_pokemons['HP']>100) | (df_pokemons['Attack']<80)].head()

## Mudança Condicional

Baseando-se nas condições que desejarmos, podemos substituir os valores de células.

Exemplo: Todo Type 1 de qualquer pokémon cujo HP seja maior que 60 será "LENDÁRIO"

In [ ]:
# Alterando um único valor
df_pokemons.loc[df_pokemons['HP'] > 60, 'Type 1'] = 'LENDARIO'

#df_pokemons.loc[df_pokemons['Type 1']=='LENDARIO'].head()
df_pokemons[df_pokemons.HP>60]['Type 1'].value_counts()

In [ ]:
# Alterando mais de 1 valor
df_pokemons.loc[df_pokemons['HP'] > 60, ['Type 1', 'Legendary']]= ['LENDARIO', True]
df_pokemons.loc[df_pokemons['HP'] > 60].head()

## Exercícios


3. Qual(is) Pokémon(s) do Type 1 Grass com maior HP?

4. Há algum pokémon do Type 1 Ghost com Sp. Atk > 60 ? 

Se sim, traga os Nomes, Type 1, Sp. Atk., HP, Legendary e Type 2. 

Ordene do maior HP para o Menor HP.

5. Há algum pokémon do Type 1 Poison e Type 2 Flying que seja Legendary?

## Exportando o Data Frame

In [ ]:
#Jupyter
# exportando para csv
df_pokemons.to_csv('pokemons_1.csv')

In [ ]:
#Colab
from google.colab import files
df_pokemons.to_csv('pokemons_1.csv')
files.download('pokemons_1.csv')